"""Add user account limits and usage tracking

Revision ID: 6fa75751c3e9
Revises: 928df475ef07
Create Date: 2025-07-08 13:26:53.721863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa75751c3e9'
down_revision: Union[str, Sequence[str], None] = '928df475ef07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('daily_usage', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_usage_date', sa.DateTime(), nullable=True))
    op.alter_column('users', 'preferences',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_spotify_id'), table_name='users')
    op.drop_column('users', 'spotify_id')
    op.drop_column('users', 'spotify_token')
    op.drop_column('users', 'spotify_refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spotify_refresh_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('spotify_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('spotify_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_spotify_id'), 'users', ['spotify_id'], unique=True)
    op.alter_column('users', 'preferences',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('users', 'last_usage_date')
    op.drop_column('users', 'daily_usage')
    op.drop_column('users', 'account_type')
    # ### end Alembic commands ###
